[package]
name = "fixed_string"
description = "Fixed-size, null-padded UTF-8 string type with const-safe construction and binary serialization support."
version = "0.1.0"
edition = "2024"
license = "MIT OR Apache-2.0"
readme = "README.md"
repository = "https://github.com/crabcode/fixed_string"
keywords = ["string", "utf8", "fixed-length", "no_std", "binrw"]
categories = ["data-structures", "encoding", "no-std"]

[features]
default = ["std"]
binrw = ["dep:binrw"]
std = []

[dependencies]
# uses Args<'a> (>=0.11.0) and BinRead/BinWrite (>=0.11.1)
# compatible with 0.14.1 (current at time of publishing)
binrw = { version = ">=0.11.1, <0.15", optional = true }